server:
  port: 8080

spring:
  application:
    name: spring-session-with-redis

  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      # No password needed for local development
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  # Spring Session Configuration
  session:
    store-type: redis
    redis:
      namespace: spring:session
      flush-mode: on_save
    timeout: 30m # 30 minutes

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,sessions
  endpoint:
    health:
      show-details: always

# Logging Configuration
logging:
  level:
    com.example: DEBUG
    org.springframework.session: DEBUG
    org.springframework.data.redis: DEBUG
    org.springframework.security: DEBUG
